CATEGORY_RULES = {
    "istituzionali": [
        "gov.it",
        "camera.it",
        "europa.eu",
        "mepa.gov.it",
        "agenziaentrate",
        "inps.it",
        "gazzettaufficiale.it",
        "normattiva.it",
        "consob.it",
        "bancaditalia.it",
        "istat.it",
        "agid.gov.it",
    ],
    "social": [
        "linkedin.com",
        "facebook.com",
        "instagram.com",
        "x.com",
    ],
    "e-commerce": ["amazon.it", "ebay.it", "etsy.com", "aliexpress.com"],
    "startup": ["startupitalia.eu", "primomaggio.it", "ilsole24ore.com"],
    "fintech": ["finextra.com", "theblock.co", "coindesk.com"],
    "gaming": ["gamesindustry.biz", "ign.com", "kotaku.com"],
    "ai": ["venturebeat.com", "techcrunch.com", "forbes.com"],
    "blockchain": ["coindesk.com", "theblock.co", "decrypt.co"],
    "cybersecurity": ["krebsonsecurity.com", "darkreading.com", "securityweek.com"],
    "finance": ["bloomberg.com", "reuters.com", "ft.com"],
    "marketing": ["adweek.com", "marketingland.com", "searchenginejournal.com"],
    "real_estate": ["zillow.com", "realtor.com", "immobiliare.it"],
    "legal": ["law360.com", "legalsites.com", "jurist.org"],
    "healthcare": ["healthcareitnews.com", "medpage.com", "medicalnewstoday.com"],
    "open_data": ["dati.gov.it", "opencorporates.com", "registroimprese.it"],
    "news": ["ansa.it", "repubblica.it", "corriere.it", "ilsole24ore.com"],
}
EXCLUDED_DOMAINS = [
    "example.com",
]
